name: 'Product Reviews'
description: 'Provides Product Reviews comment type and related configuration. '
type: module
core: 8.x
dependencies:
  - comment
  - comments_order
  - commerce_product
  - field
  - language
  - options
  - text
